# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET CodeGeassSolution.sln
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies CodeGeass.Api
      run: dotnet restore projects/server/src/CodeGeass.Api/CodeGeass.Api.csproj
    - name: Build CodeGeass.Api
      run: dotnet build projects/server/src/CodeGeass.Api/CodeGeass.Api.csproj --no-restore 
    - name: Test CodeGeass.Api
      run: dotnet test projects/server/src/CodeGeass.Api/CodeGeass.Api.csproj --no-build --verbosity normal
    - name: Restore dependencies CodeGeass.KnightmareFrames.Api
      run: dotnet restore projects/server/src/CodeGeass.KnightmareFrames.Api/CodeGeass.KnightmareFrames.Api.csproj
    - name: Build CodeGeass.KnightmareFrames.Api
      run: dotnet build projects/server/src/CodeGeass.KnightmareFrames.Api/CodeGeass.KnightmareFrames.Api.csproj --no-restore 
    - name: Test CodeGeass.KnightmareFrames.Api
      run: dotnet test projects/server/src/CodeGeass.KnightmareFrames.Api/CodeGeass.KnightmareFrames.Api.csproj --no-build --verbosity normal 
